### ISSUE TITLE
Bug - Chocolate Syrup Doesn't Burn in Excess of 1000 degrees

### ISSUE THREAD

**Issue by smurfhunter** [slweeb/sandboxels#10]
Shouldn't chocolate syrup melt or catch fire if it's that hot or am I crazy

**Comment by slweeb** [comment]
Chocolate syrup is a liquid, so I'm not sure what it should do

**Comment by slweeb** [comment]
Any ideas? Most other liquids now evaporate into something, but not syrup

**Comment by smurfhunter** [comment]
Hey! Sorry for the late response - I asked my friend with a bachelors related to chemistry - his suggestion was to have it boil just under the temperature of water and leave something sugar related and steam as byproducts - for the most part, it is made of sugar and steam. Perhaps something like carbon/hydrogen and steam since those are sugar's main components? Or just a generic carmel/sugar solid?

**Comment by slweeb** [comment]
hi! no problem! there is a sugar element now so that is a good idea, thanks! he should check out the game, a chemistry major could have some good insight. closing the issue then, but my discord is ryan#4755 if anyone needs anything
