### ISSUE TITLE
Error - "Uncaught TypeError: rgb is null"

### ISSUE THREAD

**Issue by StellarX20** [slweeb/sandboxels#11]
I don't know what this means, but it causes the game to be unplayable, please fix this.
![image](https://user-images.githubusercontent.com/97905447/149835107-f740ec63-df47-431e-8157-ca7992abaa99.png)
![image](https://user-images.githubusercontent.com/97905447/149835121-26763622-5f91-4377-8d42-affdb609284e.png)
![image](https://user-images.githubusercontent.com/97905447/149835148-ce2d1be7-fec8-4c67-85fa-d50585d90654.png)
![image](https://user-images.githubusercontent.com/97905447/149835170-163e284c-d857-49c1-8830-8757cd04158a.png)
![image](https://user-images.githubusercontent.com/97905447/149835186-89698ca1-5855-4d54-bcd0-9178fc62fcb4.png)
![image](https://user-images.githubusercontent.com/97905447/149835207-165a2180-d9ab-40da-a5a8-58ee133b2c2e.png)
This error happens in vanilla: 
![image](https://user-images.githubusercontent.com/97905447/149835225-1cedf867-7420-4229-821b-77a9c0518954.png)

**Comment by slweeb** [comment]
note: problem with their mod
